
INSERT INTO Pilote (nom, prenom, numPil, paysPil) VALUES
	('Verstappen', 'Max', '1', 'Pays-Bas'),
	('Perez', 'Sergio', '11', 'Mexique'),
    ('Hamilton', 'Lewis', '44', 'Royaume-Uni'),
	('Alonso','Fernando', '14', 'Espagnol'),
    ('Norris', 'Lando', '4', 'Royaume-Uni'),
    ('Sainz', 'Carlos', '55', 'Espagne'),
    ('Leclerc', 'Charles', '16', 'Monaco'),
    ('Russel', 'George', '63', 'Royaume-Uni'),
    ('Piastri', 'Oscar', '81', 'Australie'),
    ('Flâner', 'Lance', '18', 'Canada'),
    ('Gasly', 'Pierre', '10', 'France'),
    ('Ocon', 'Estéban', '31', 'France'),
    ('Albon', 'Alexandre', '23', 'Thailande'),
    ('Tsunoda', 'Yuki', '22', 'Japon'),
    ('Bottas', 'Valtteri', '77', 'Finlande'),
    ('Hülkenberg', 'Nico', '27', 'Allemagne'),
    ('Ricciardo', 'Daniel', '3', 'Australie'),
    ('Zhou', 'Guan Yu', '24', 'Chine'),
    ('Magnussen', 'Kevin', '20', 'Dannemark'),
    ('Lawson', 'Liam', '40', 'Nouvelle-Zélande'),
    ('Sargeant', 'Logan', '2', 'Etats-Unis'),
    ('De Vries', 'Nyck', '24', 'Pays-Bas'),
    ('Vettel', 'Sebastian', '5', 'Allemagne'),
    ('Schumacher', 'Mick', '47', 'Allemagne'),
    ('Latifi', 'Nicholas', '6', 'Canada'),
    ('Räikkönen', 'Kimi', '7', 'Finlande'),
    ('Giovinazzi', 'Antonio', '50', 'Italie'),
    ('Kubica', 'Robert', '21', 'Pologne'),
    ('Mazepin', 'Nikita', '9', 'Russe'),
    ('Kvyat', 'Daniil', '26', 'Russe'),
    ('Grosjean', 'Romain', '8', 'France'),
    ('Aitken', 'Jack', '89', 'Royaume-Uni'),
    ('Fittipaldi', 'Pietro', '51', 'Brésil'),
    ('Vandoorne', 'Stoffel', '11', 'Belgique'),
    ('Ericsson', 'Marcus', '9', 'Suède'),
    ('Hartley', 'Brendon', '28', 'Nouvelle-Zélande'),
    ('Sirotkin', 'Sergey', '35', 'Russe');
    
    
    
    