USE bdTheNorthRace;
INSERT INTO Pilote (nom, prenom, paysPil) VALUES
    ('Verstappen', 'Max', 'Pays-Bas'),
    ('Perez', 'Sergio', 'Mexique'),
    ('Hamilton', 'Lewis', 'Royaume-Uni'),
    ('Alonso', 'Fernando', 'Espagnol'),
    ('Norris', 'Lando', 'Royaume-Uni'),
    ('Sainz', 'Carlos', 'Espagne'),
    ('Leclerc', 'Charles', 'Monaco'),
    ('Russel', 'George', 'Royaume-Uni'),
    ('Piastri', 'Oscar', 'Australie'),
    ('Flâner', 'Lance', 'Canada'),
    ('Gasly', 'Pierre', 'France'),
    ('Ocon', 'Estéban', 'France'),
    ('Albon', 'Alexandre', 'Thailande'),
    ('Tsunoda', 'Yuki', 'Japon'),
    ('Bottas', 'Valtteri', 'Finlande'),
    ('Hülkenberg', 'Nico', 'Allemagne'),
    ('Ricciardo', 'Daniel', 'Australie'),
    ('Zhou', 'Guan Yu', 'Chine'),
    ('Magnussen', 'Kevin', 'Dannemark'),
    ('Lawson', 'Liam', 'Nouvelle-Zélande'),
    ('Sargeant', 'Logan', 'Etats-Unis'),
    ('De Vries', 'Nyck', 'Pays-Bas'),
    ('Vettel', 'Sebastian', 'Allemagne'),
    ('Schumacher', 'Mick', 'Allemagne'),
    ('Latifi', 'Nicholas', 'Canada'),
    ('Räikkönen', 'Kimi', 'Finlande'),
    ('Giovinazzi', 'Antonio', 'Italie'),
    ('Kubica', 'Robert', 'Pologne'),
    ('Mazepin', 'Nikita', 'Russe'),
    ('Kvyat', 'Daniil', 'Russe'),
    ('Grosjean', 'Romain', 'France'),
    ('Aitken', 'Jack', 'Royaume-Uni'),
    ('Fittipaldi', 'Pietro', 'Brésil'),
    ('Vandoorne', 'Stoffel', 'Belgique'),
    ('Ericsson', 'Marcus', 'Suède'),
    ('Hartley', 'Brendon', 'Nouvelle-Zélande'),
    ('Sirotkin', 'Sergey', 'Russe');