-- 2023
INSERT INTO Pilote (nom, prenom, paysPil) VALUES
	
    ('Verstappen', 'Max', 'Pays-Bas'),
	('Perez', 'Sergio', 'Mexique'),
    ('Hamilton', 'Lewis', 'Royaume-Uni'),
	('Alonso', 'Fernando', 'Espagnol'),
    ('Norris', 'Lando', 'Royaume-Uni'),
    ('Sainz', 'Carlos', 'Espagne'),
    ('Leclerc', 'Charles', 'Monaco'),
    ('Russel', 'George', 'Royaume-Uni'),
    ('Piastri', 'Oscar', 'Australie'),
    ('Stroll', 'Lance', 'Canada'),
    ('Gasly', 'Pierre', 'France'),
    ('Ocon', 'Estéban', 'France'),
    ('Albon', 'Alexandre', 'Thailande'),
    ('Tsunoda', 'Yuki', 'Japon'),
    ('Bottas', 'Valtteri', 'Finlande'),
    ('Hülkenberg', 'Nico', 'Allemagne'),
    ('Ricciardo', 'Daniel', 'Australie'),
    ('Zhou', 'Guan Yu', 'Chine'),
    ('Magnussen', 'Kevin', 'Dannemark'),
    ('Lawson', 'Liam', 'Nouvelle-Zélande'),
    ('Sargeant', 'Logan', 'Etats-Unis'),
    ('De Vries', 'Nyck', 'Pays-Bas'),
    
    
       -- Pilote de l'année 2022
    
    -- ('Verstappen', 'Max', 'Pays-Bas'),
    -- ('Leclerc', 'Charles', 'Monaco'),
    -- ('Perez', 'Sergio', 'Mexique'),
    -- ('Russel', 'George', 'Royaume-Uni'),
    -- ('Sainz', 'Carlos', 'Espagne'),
    -- ('Hamilton', 'Lewis', 'Royaume-Uni'),
    -- ('Norris', 'Lando', 'Royaume-Uni'),
    -- ('Ocon', 'Estéban', 'France'),
    -- ('Alonso','Fernando', 'Espagnol'),
    -- ('Bottas', 'Valtteri', 'Finlande'),
    -- ('Ricciardo', 'Daniel', 'Australie'),
    ('Vettel', 'Sebastian', 'Allemagne'),
    -- ('Magnussen', 'Kevin', 'Dannemark'),
    -- ('Gasly', 'Pierre', 'France'),
    -- ('Stroll', 'Lance', 'Canada'),
    ('Schumacher', 'Mick', 'Allemagne'),
    -- ('Tsunoda', 'Yuki', 'Japon'),
    -- ('Zhou', 'Guan Yu', 'Chine'),
    -- ('Albon', 'Alexandre', 'Thailande'),
    ('Latifi', 'Nicholas', 'Canada'),
    -- ('De Vries', 'Nyck', 'Pays-Bas'),
    -- ('Hülkenberg', 'Nico', 'Allemagne'),
    
    
     -- Pilote de l'année 2021
     
	-- ('Verstappen', 'Max', 'Pays-Bas'),
    -- ('Hamilton', 'Lewis', 'Royaume-Uni'),
    -- ('Bottas', 'Valtteri', 'Finlande'),
    -- ('Perez', 'Sergio', 'Mexique'),
    -- ('Sainz', 'Carlos', 'Espagne'),
    -- ('Norris', 'Lando', 'Royaume-Uni'),
    -- ('Leclerc', 'Charles', 'Monaco'),
    -- ('Ricciardo', 'Daniel', 'Australie'),
    -- ('Gasly', 'Pierre', 'France'),
    -- ('Alonso','Fernando', 'Espagnol'),
    -- ('Ocon', 'Estéban', 'France'),
    -- ('Vettel', 'Sebastian', 'Allemagne'),
    -- ('Stroll', 'Lance', 'Canada'),
    -- ('Tsunoda', 'Yuki', 'Japon'),
    -- ('Russel', 'George', 'Royaume-Uni'),
    ('Räikkönen', 'Kimi', 'Finlande'),
    -- ('Latifi', 'Nicholas', 'Canada'),
    ('Giovinazzi', 'Antonio', 'Italie'),
    -- ('Schumacher', 'Mick', 'Allemagne'),
    ('Kubica', 'Robert', 'Pologne'),
    ('Mazepin', 'Nikita', 'Russe'),
    
    
-- Pilote de l'année 2020

-- ('Hamilton', 'Lewis', 'Royaume-Uni'),
-- ('Bottas', 'Valtteri', 'Finlande'),
-- ('Verstappen', 'Max', 'Pays-Bas'),
-- ('Perez', 'Sergio', 'Mexique'),
-- ('Ricciardo', 'Daniel', 'Australie'),
-- ('Sainz', 'Carlos', 'Espagne'),
-- ('Albon', 'Alexandre', 'Thailande'),
-- ('Leclerc', 'Charles', 'Monaco'),
-- ('Norris', 'Lando', 'Royaume-Uni'),
-- ('Gasly', 'Pierre', 'France'),
-- ('Stroll', 'Lance', 'Canada'),
-- ('Ocon', 'Estéban', 'France'),
-- ('Vettel', 'Sebastian', 'Allemagne'),
('Kvyat', 'Daniil', 'Russe'),
-- ('Hülkenberg', 'Nico', 'Allemagne'),
-- ('Räikkönen', 'Kimi', 'Finlande'),
-- ('Giovinazzi', 'Antonio', 'Italie'),
-- ('Russel', 'George', 'Royaume-Uni'),
('Grosjean', 'Romain', 'France'),
-- ('Magnussen', 'Kevin', 'Dannemark'),
('Aitken', 'Jack', 'Royaume-Uni'),
('Fittipaldi', 'Pietro', 'Brésil'),

-- Pilote de l'année 2019

-- ('Hamilton', 'Lewis', 'Royaume-Uni'),
-- ('Bottas', 'Valtteri', 'Finlande'),
-- ('Verstappen', 'Max', 'Pays-Bas'),
-- ('Leclerc', 'Charles', 'Monaco'),
-- ('Vettel', 'Sebastian', 'Allemagne'),
-- ('Sainz', 'Carlos', 'Espagne'),
-- ('Gasly', 'Pierre', 'France'),
-- ('Albon', 'Alexandre', 'Thailande'),
-- ('Ricciardo', 'Daniel', 'Australie'),
-- ('Perez', 'Sergio', 'Mexique'),
-- ('Norris', 'Lando', 'Royaume-Uni'),
-- ('Räikkönen', 'Kimi', 'Finlande'),
-- ('Kvyat', 'Daniil', 'Russe'),
-- ('Hülkenberg', 'Nico', 'Allemagne'),
-- ('Stroll', 'Lance', 'Canada'),
-- ('Magnussen', 'Kevin', 'Dannemark'),
-- ('Giovinazzi', 'Antonio', 'Italie'),
-- ('Grosjean', 'Romain', 'France'),
-- ('Kubica', 'Robert', 'Pologne'),
-- ('Russel', 'George', 'Royaume-Uni'),

-- Pilote de l'année 2018

-- ('Hamilton', 'Lewis', 'Royaume-Uni'),
-- ('Vettel', 'Sebastian', 'Allemagne'),
-- ('Räikkönen', 'Kimi', 'Finlande'),
-- ('Verstappen', 'Max', 'Pays-Bas'),
-- ('Bottas', 'Valtteri', 'Finlande'),
-- ('Ricciardo', 'Daniel', 'Australie'),
-- ('Hülkenberg', 'Nico', 'Allemagne'),
-- ('Perez', 'Sergio', 'Mexique'),
-- ('Magnussen', 'Kevin', 'Dannemark'),
-- ('Sainz', 'Carlos', 'Espagne'),
-- ('Alonso','Fernando', 'Espagnol'),
-- ('Ocon', 'Estéban', 'France'),
-- ('Leclerc', 'Charles', 'Monaco'),
-- ('Grosjean', 'Romain', 'France'),
-- ('Gasly', 'Pierre', 'France'),
('Vandoorne', 'Stoffel', 'Belgique'),
('Ericsson', 'Marcus', 'Suède'),
-- ('Stroll', 'Lance', 'Canada'),
('Hartley', 'Brendon', 'Nouvelle-Zélande'),
('Sirotkin', 'Sergey', 'Russe');
